"""empty message

Revision ID: 762d5bb286ab
Revises: 30316dd825b6
Create Date: 2019-06-11 18:43:26.684916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762d5bb286ab'
down_revision = '30316dd825b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
