"""empty message

Revision ID: 081e0949ba21
Revises: 
Create Date: 2019-05-07 19:38:03.763647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '081e0949ba21'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('strength', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coffee')
    # ### end Alembic commands ###
